<?php

namespace AppBundle\Repository;

/**
 * RecurringEmployeeFeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecurringEmployeeFeedbackRepository extends \Doctrine\ORM\EntityRepository
{
}
