parameters:
    knp_menu.renderer.twig.options:
        currentClass: active

services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    unappointed_feedback_consumer:
        class: AppBundle\Consumer\UnappointedFeedbackConsumer
